services:
    n8n:
        image: n8nio/n8n
        restart: always
        ports:
            - "5678:5678"
        volumes:
            - n8n_data:/home/node/.n8n
        command: ["start"]
        environment:
        - N8N_HOST=c088e17d7ac9.ngrok-free.app
        - WEBHOOK_URL=https://c088e17d7ac9.ngrok-free.app
        - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
        - DB_SQLITE_POOL_SIZE=10
        - N8N_RUNNERS_ENABLED=true
        - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
        - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
        - N8N_TRUSTED_PROXIES=*
volumes:
    n8n_data: {}